In [1]:
import numpy as np
a = np.random.randn(5)

In [6]:
print a

[  6.09066188e-04  -1.44635485e+00  -2.01347542e-02  -1.57721220e+00
   1.08197973e+00]


In [8]:
print a.shape

(5,)


In [10]:
print a.T # 秩为1的数组

[  6.09066188e-04  -1.44635485e+00  -2.01347542e-02  -1.57721220e+00
   1.08197973e+00]


In [12]:
print a.shape

(5,)


In [14]:
print np.dot(a,a.T)

5.75062659155


In [17]:
b = np.random.randn(5,1)

In [21]:
print b # np.random.randn(5)和np.random.randn(5,1)两者得到的结果是不同的，而第一种情况可能会带来更多bug

[[ 0.03045338]
 [ 0.07209747]
 [ 0.4320537 ]
 [-0.7659126 ]
 [ 0.26135994]]


In [23]:
print b.T # 1x5维的矩阵

[[ 0.03045338  0.07209747  0.4320537  -0.7659126   0.26135994]]


In [26]:
print np.dot(b,b.T)

[[ 0.00092741  0.00219561  0.01315749 -0.02332463  0.00795929]
 [ 0.00219561  0.00519805  0.03114998 -0.05522036  0.01884339]
 [ 0.01315749  0.03114998  0.1866704  -0.33091537  0.11292153]
 [-0.02332463 -0.05522036 -0.33091537  0.58662211 -0.20017887]
 [ 0.00795929  0.01884339  0.11292153 -0.20017887  0.06830902]]
